### PR TITLE
Added Personal CV Website

### PR DESCRIPTION
**Pull request by iamwicked**

### CODE REVIEW

**Comment by iamwicked** [comment]
Please merge this Pull Request

**Comment by Priyadarshan2000** [comment]
@iamwicked update ..?

**Comment by iamwicked** [comment]
I have made a Personal Portfolio Website using HTML and CSS.

**Comment by Priyadarshan2000** [comment]
> I have made a Personal Portfolio Website using HTML and CSS.

@iamwicked  rename index.html file

**Comment by iamwicked** [comment]
I have changed the name of index.html. Please merge this pull request

**Comment by Priyadarshan2000** [comment]
ya sure

**Pull request merged**
