### PR TITLE
calculator

### PR DESCRIPTION
**Pull request by horerick46**
a simple calculator using html, css and javascript.

### CODE REVIEW

**Comment by Priyadarshan2000** [comment]
@horerick46 rename the file name index.html

**Comment by horerick46** [comment]
which file??

**Comment by horerick46** [comment]
@Priyadarshan2000 which file?

**Comment by Priyadarshan2000** [comment]
@horerick46 index.html file rename that file

**Comment by horerick46** [comment]
its changed now.

**Comment by horerick46** [comment]
@Priyadarshan2000 its changed.

**Pull request merged**
